"""Initial migration

Revision ID: 392e5bb505d3
Revises:
Create Date: 2025-04-13 01:17:35.545052

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "392e5bb505d3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlist_entries_new",
        sa.Column("playlist_id", sa.Text(), nullable=False),
        sa.Column("video_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["playlist_id"], ["playlists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["video_id"], ["videos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("playlist_id", "video_id"),
    )

    op.create_table(
        "playlists_new",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "last_updated",
            sa.Text(),
            nullable=False,
            server_default=sa.func.datetime("now", "utc"),
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.text("1")),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "videos_new",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("uploader", sa.Text(), nullable=True),
        sa.Column("duration", sa.REAL(), nullable=True),
        sa.Column("upload_date", sa.Text(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("video_file", sa.Text(), nullable=True),
        sa.Column("thumbnail", sa.Text(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=False, server_default=sa.text("0")),
        sa.Column(
            "last_updated",
            sa.Text(),
            nullable=False,
            server_default=sa.func.datetime("now", "utc"),
        ),
        sa.Column(
            "downloaded", sa.Boolean(), nullable=False, server_default=sa.text("0")
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Copy data from old tables to new ones
    op.execute(
        "INSERT INTO playlist_entries_new SELECT playlist_id, video_id FROM playlist_entries"
    )
    op.execute(
        "INSERT INTO playlists_new SELECT id, title, description, last_updated, enabled FROM playlists"
    )
    op.execute("""
        INSERT INTO videos_new
        SELECT
            id,
            title,
            description,
            uploader,
            duration,
            upload_date,
            width,
            height,
            video_file,
            thumbnail,
            COALESCE(deleted, 0),
            COALESCE(last_updated, datetime('now', 'utc')),
            COALESCE(downloaded, 0)
        FROM videos
    """)

    # Drop old tables
    op.drop_table("playlist_entries")
    op.drop_table("playlists")
    op.drop_table("videos")

    # Rename new tables to original names
    op.rename_table("playlist_entries_new", "playlist_entries")
    op.rename_table("playlists_new", "playlists")
    op.rename_table("videos_new", "videos")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("videos", sa.Column("comment_count", sa.INTEGER(), nullable=True))
    op.add_column("videos", sa.Column("like_count", sa.INTEGER(), nullable=True))
    op.add_column("videos", sa.Column("ranking", sa.INTEGER(), nullable=True))
    op.add_column("videos", sa.Column("view_count", sa.INTEGER(), nullable=True))
    op.add_column(
        "videos",
        sa.Column(
            "comment_count_estimated",
            sa.INTEGER(),
            server_default=sa.text("0"),
            nullable=True,
        ),
    )
    op.alter_column(
        "videos",
        "downloaded",
        existing_type=sa.Boolean(),
        type_=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column("videos", "last_updated", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "videos",
        "deleted",
        existing_type=sa.Boolean(),
        type_=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column("videos", "title", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("videos", "id", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "playlists",
        "enabled",
        existing_type=sa.Boolean(),
        type_=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("1"),
    )
    op.alter_column("playlists", "last_updated", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("playlists", "title", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("playlists", "id", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "playlist_entries", "video_id", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "playlist_entries", "playlist_id", existing_type=sa.TEXT(), nullable=True
    )
    # ### end Alembic commands ###
