"""re-add last_updated to track table

Revision ID: 5328ad3ee60f
Revises: 8a17ace0170e
Create Date: 2025-04-15 13:25:51.627344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5328ad3ee60f'
down_revision: Union[str, None] = '8a17ace0170e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discogs_track', sa.Column('last_updated', sa.Text(), server_default=sa.text("(datetime('now', 'utc'))"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discogs_track', 'last_updated')
    # ### end Alembic commands ###
