"""make_discogs_track_id_autoincrement

Revision ID: 82a71c181aee
Revises: 5328ad3ee60f
Create Date: 2025-04-15 13:44:18.195977

"""
from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = '82a71c181aee'
down_revision: str | None = '5328ad3ee60f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
