"""resync_schema

Revision ID: 8c74b7f98837
Revises: 13346968846a
Create Date: 2025-04-15 02:57:55.905855

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c74b7f98837"
down_revision: Union[str, None] = "13346968846a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "videos_new",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("uploader", sa.Text(), nullable=True),
        sa.Column("duration", sa.REAL(), nullable=True),
        sa.Column("upload_date", sa.Text(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("video_file", sa.Text(), nullable=True),
        sa.Column("thumbnail", sa.Text(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=False, server_default=sa.text("0")),
        sa.Column(
            "last_updated",
            sa.Text(),
            nullable=False,
            server_default=sa.func.datetime("now", "utc"),
        ),
        sa.Column(
            "downloaded", sa.Boolean(), nullable=False, server_default=sa.text("0")
        ),
        sa.Column("discogs_track_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["discogs_track_id"],
            ["discogs_track.id"],
        ),
    )
    op.execute("""
        INSERT INTO videos_new
        SELECT
            id,
            title,
            description,
            uploader,
            duration,
            upload_date,
            width,
            height,
            video_file,
            thumbnail,
            COALESCE(deleted, 0),
            COALESCE(last_updated, datetime('now', 'utc')),
            COALESCE(downloaded, 0),
            null
        FROM videos
    """)
    op.drop_table("videos")
    op.rename_table("videos_new", "videos")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "videos", type_="foreignkey")
    op.drop_column("videos", "discogs_track_id")
    # ### end Alembic commands ###
