"""Rename DiscogXxx to DiscogsXxx

Revision ID: c78f2a13f4b5
Revises: d9d22a90d621
Create Date: 2025-04-14 23:12:33.995597

"""
from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = 'c78f2a13f4b5'
down_revision: str | None = 'd9d22a90d621'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
