"""Rename DiscogXxx to DiscogsXxx

Revision ID: c78f2a13f4b5
Revises: d9d22a90d621
Create Date: 2025-04-14 23:12:33.995597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c78f2a13f4b5'
down_revision: Union[str, None] = 'd9d22a90d621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
