"""Add discogs tables

Revision ID: d9d22a90d621
Revises: 392e5bb505d3
Create Date: 2025-04-13 16:42:20.182412

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9d22a90d621"
down_revision: str | None = "392e5bb505d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discogs_artist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("profile", sa.Text(), nullable=True),
        sa.Column("uri", sa.Text(), nullable=False),
        sa.Column(
            "last_updated",
            sa.Text(),
            server_default=sa.text("(datetime('now', 'utc'))"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "discogs_release",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("released", sa.Integer(), nullable=False),
        sa.Column("country", sa.Text(), nullable=False),
        sa.Column("genre", sa.JSON(), nullable=True),
        sa.Column("style", sa.JSON(), nullable=True),
        sa.Column("uri", sa.Text(), nullable=False),
        sa.Column(
            "last_updated",
            sa.Text(),
            server_default=sa.text("(datetime('now', 'utc'))"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "discogs_track",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("duration", sa.Text(), nullable=True),
        sa.Column("position", sa.Text(), nullable=False),
        sa.Column("type_", sa.Text(), nullable=False),
        sa.Column("release_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["discogs_release.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "release_artists",
        sa.Column("release_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.Text(), nullable=True),
        sa.Column("is_main", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["discogs_artist.id"],
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["discogs_release.id"],
        ),
        sa.PrimaryKeyConstraint("release_id", "artist_id"),
    )

    op.create_table(
        "videos_new",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("uploader", sa.Text(), nullable=True),
        sa.Column("duration", sa.REAL(), nullable=True),
        sa.Column("upload_date", sa.Text(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("video_file", sa.Text(), nullable=True),
        sa.Column("thumbnail", sa.Text(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=False, server_default=sa.text("0")),
        sa.Column(
            "last_updated",
            sa.Text(),
            nullable=False,
            server_default=sa.func.datetime("now", "utc"),
        ),
        sa.Column(
            "downloaded", sa.Boolean(), nullable=False, server_default=sa.text("0")
        ),
        sa.Column("discogs_track_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["discogs_track_id"],
            ["discogs_track.id"],
        ),
    )
    op.execute("""
        INSERT INTO videos_new
        SELECT
            id,
            title,
            description,
            uploader,
            duration,
            upload_date,
            width,
            height,
            video_file,
            thumbnail,
            COALESCE(deleted, 0),
            COALESCE(last_updated, datetime('now', 'utc')),
            COALESCE(downloaded, 0),
            null
        FROM videos
    """)
    op.drop_table("videos")
    op.rename_table("videos_new", "videos")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "videos", type_="foreignkey")
    op.drop_column("videos", "discogs_track_id")
    op.drop_table("release_artists")
    op.drop_table("discogs_track")
    op.drop_table("discogs_release")
    op.drop_table("discogs_artist")
    # ### end Alembic commands ###
