"""Remove relationship 

Revision ID: fd51db28df23
Revises: c78f2a13f4b5
Create Date: 2025-04-14 23:13:17.486982

"""
from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = 'fd51db28df23'
down_revision: str | None = 'c78f2a13f4b5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
