version: "3"

vars:
  ALL: src/tools/ tests/
  VENV: .venv/bin
  SOURCES: src/tools/
  TESTS: tests/

tasks:
  ruff:
    desc: "Run ruff"
    cmds:
      - "{{.VENV}}/ruff check {{.SOURCES}}"
      - "{{.VENV}}/ruff format {{.SOURCES}}"
      - "{{.VENV}}/ruff check {{.TESTS}}"
      - "{{.VENV}}/ruff format {{.TESTS}}"

  ruff-fix:
    desc: "fix ruff issues"
    cmds:
      - "{{.VENV}}/ruff check {{.SOURCES}} --fix"
      - "{{.VENV}}/ruff format {{.SOURCES}}"
      - "{{.VENV}}/ruff check {{.TESTS}} --fix"
      - "{{.VENV}}/ruff format {{.TESTS}}"

  # Task to open the latest coverage report in a web browser
  coverage:
    desc: "Open the latest coverage report in a web browser"
    cmds:
      - open tests/coverage/index.html

  # Task to run all linting tasks (ruff, ty)
  lint:
    desc: "Run all linting tasks"
    deps:
      - ruff
      - ty

  # Task to run ty for static type checking on the source code
  ty:
    desc: "Run ty for static type checking"
    cmds:
      - "{{.VENV}}/ty check {{.SOURCES}}"
      - "{{.VENV}}/ty check {{.TESTS}}"

  # Task to run linting and tests
  qa:
    desc: "Run linting and tests"
    deps:
      - test
      - lint

  # Task to run tests using pytest with coverage reporting
  test:
    desc: "Run tests with coverage"
    cmds:
      - pytest -vv --cov --cov-report=html:tests/coverage --cov-fail-under=95 $(if [ -n "{{.CLI_ARGS}}" ]; then echo "{{.CLI_ARGS}}"; else echo .; fi)
