version: "3"

vars:
  VENV: venv/bin
  SOURCES: tools/ tests/

tasks:
  black:
    desc: "lint Python code with Black"
    cmds:
      - "{{.VENV}}/black {{.SOURCES}}"

  coverage:
    desc: "opens the latest coverage in a web browser"
    cmds:
      - open tests/coverage/index.html

  flake8:
    desc: "lint Python code with flake"
    cmds:
      - "{{.VENV}}/flake8 {{.SOURCES}}"

  isort:
    desc: "sorts import"
    cmds:
      - "{{.VENV}}/isort {{.SOURCES}}"

  test:
    cmds:
      - pytest -vv --cov --cov-report=html:tests/coverage --cov-fail-under=95 .
