version: "3"

vars:
  ALL: tools/ tests/
  VENV: venv/bin
  SOURCES: tools/

tasks:
  bandit:
    desc: ""
    cmds:
      - "{{.VENV}}/bandit {{.SOURCES}}"

  black:
    desc: "lint Python code with Black"
    cmds:
      - "{{.VENV}}/black {{.ALL}}"

  coverage:
    desc: "opens the latest coverage in a web browser"
    cmds:
      - open tests/coverage/index.html

  flake8:
    desc: "lint Python code with flake"
    cmds:
      - "{{.VENV}}/flake8 {{.ALL}}"

  isort:
    desc: "sorts imports"
    cmds:
      - "{{.VENV}}/isort {{.ALL}}"

  lint:
    desc: "runs all linting tasks"
    deps:
      - isort
      - black
      - mypy
      - flake8
      - bandit

  mypy:
    desc: "runs mypy on source"
    cmds:
      - "{{.VENV}}/mypy {{.SOURCES}}"

  qa:
    desc: "runs linting and test"
    deps:
      - test
      - lint

  test:
    cmds:
      - pytest -vv --cov --cov-report=html:tests/coverage --cov-fail-under=95 .
